version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: debezium
      MYSQL_PASSWORD: dbz
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--binlog-format=ROW",
        "--binlog-row-image=FULL",
        "--gtid-mode=ON",
        "--enforce-gtid-consistency=ON",
        "--log-bin=mysql-bin.log",
        "--server-id=1",
      ]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kafka-connect:
    image: debezium/connect:1.9
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "docker-connect-configs"
      OFFSET_STORAGE_TOPIC: "docker-connect-offsets"
      STATUS_STORAGE_TOPIC: "docker-connect-status"
      BOOTSTRAP_SERVERS: "kafka:9092"
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      PLUGIN_PATH: "/kafka/connect"
    depends_on:
      - kafka
    volumes:
      - ./plugins:/kafka/connect

volumes:
  esdata:
    driver: local
